let TERMS=[];
let lang=localStorage.getItem('emcpLang')||'tr',activeCat='Tümü',mode='all';
const norm=s=>String(s||'').toLocaleLowerCase('tr-TR').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i').replace(/ş/g,'s').replace(/ç/g,'c').replace(/ğ/g,'g').replace(/ö/g,'o').replace(/ü/g,'u');
const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function score(t,q){if(!q)return 1;const n=norm(q),term=norm(t.term),abbr=norm(t.abbr),tr=norm(t.tr),tags=norm((t.tags||[]).join(' ')),def=norm(t.def);let s=0;if(term===n)s+=100;if(abbr===n)s+=95;if(term.startsWith(n))s+=70;if(abbr.startsWith(n))s+=65;if(tr.startsWith(n))s+=55;if(term.includes(n))s+=45;if(abbr.includes(n))s+=40;if(tr.includes(n))s+=35;if(tags.includes(n))s+=25;if(def.includes(n))s+=15;return s;}
function getFav(){return JSON.parse(localStorage.getItem('emcpFav')||'[]')}function getRecent(){return JSON.parse(localStorage.getItem('emcpRecent')||'[]')}
function updateStats(){favCount.textContent=getFav().length;recentCount.textContent=getRecent().length}
function renderCats(){cats.innerHTML=['Tümü',...new Set(TERMS.map(x=>x.cat))].map(c=>`<button class="chip ${activeCat===c?'active':''}" onclick="setCat('${c.replace(/'/g,"\'")}')">${esc(c)}</button>`).join('')}
function getList(){const q=document.getElementById('q').value.trim();let a=TERMS.map((t,i)=>({...t,_i:i,_s:score(t,q)})).filter(x=>x._s>0);if(activeCat!=='Tümü')a=a.filter(x=>x.cat===activeCat);a.sort((a,b)=>b._s-a._s||a.term.localeCompare(b.term,'en'));return a}
function render(){const a=getList();count.textContent=lang==='tr'?`${a.length} sonuç`:`${a.length} results`;grid.innerHTML=a.length?a.map((t,n)=>`<article class="card" style="animation-delay:${Math.min(n,8)*30}ms" onclick="openTerm(${t._i})"><div class="term">${esc(t.term)}</div>${t.abbr?`<div class="abbr">${esc(t.abbr)}</div>`:''}<div class="tr">${esc(t.tr)}</div><div class="def">${esc(t.def)}</div><div class="badge">${esc(t.cat)}</div></article>`).join(''):`<div class="empty">${lang==='tr'?'Sonuç bulunamadı.':'No results found.'}</div>`;updateStats()}
function setCat(c){activeCat=c;renderCats();render()}
function openTerm(i){const t=TERMS[i];let r=getRecent();r=[t.term,...r.filter(x=>x!==t.term)].slice(0,30);localStorage.setItem('emcpRecent',JSON.stringify(r));const fav=getFav().includes(t.term);sheet.innerHTML=`<button class="close" onclick="closeModal()">×</button><div class="badge">${esc(t.cat)}</div><h2>${esc(t.term)}</h2>${t.abbr?`<div class="abbr">${esc(t.abbr)}</div>`:''}<h3>${lang==='tr'?'Türkçesi':'Turkish equivalent'}</h3><p><b>${esc(t.tr)}</b></p><h3>${lang==='tr'?'Tanım':'Definition'}</h3><p>${esc(t.def)}</p><h3>${lang==='tr'?'Ne zaman kullanılır?':'When is it used?'}</h3><p>${esc(t.use)}</p><h3>${lang==='tr'?'Toplantı / e-posta örneği':'Meeting / email example'}</h3><p><i>${esc(t.example)}</i></p><div class="actions"><button onclick="toggleFav('${t.term.replace(/'/g,"\'")}')">${fav?'★':'☆'} Favourite</button><button onclick="copyTerm(${i})">Copy</button><button onclick="shareTerm(${i})">Share</button></div>`;modal.classList.add('show');updateStats()}
function closeModal(){modal.classList.remove('show')}function toggleFav(term){let f=getFav();f=f.includes(term)?f.filter(x=>x!==term):[...f,term];localStorage.setItem('emcpFav',JSON.stringify(f));closeModal();render()}
function copyTerm(i){const t=TERMS[i];navigator.clipboard?.writeText(`${t.term} — ${t.tr}\n${t.def}`);alert(lang==='tr'?'Kopyalandı':'Copied')}
function shareTerm(i){const t=TERMS[i],text=`${t.term} — ${t.tr}\n${t.def}`;if(navigator.share)navigator.share({title:t.term,text});else copyTerm(i)}
function showPage(name){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));document.getElementById('page-'+name).classList.add('active');document.querySelectorAll('.bottom button').forEach(b=>b.classList.remove('active'));if(name==='home')navHome.classList.add('active');if(name==='knowledge')navKnowledge.classList.add('active');if(name==='calculators')navCalc.classList.add('active');if(name==='construction')navBuild.classList.add('active');scrollTo({top:0,behavior:'smooth'})}
function setLang(l){lang=l;localStorage.setItem('emcpLang',l);trBtn.classList.toggle('active',l==='tr');enBtn.classList.toggle('active',l==='en');q.placeholder=l==='tr'?'Bir harf, kelime veya kısaltma yazın…':'Type a letter, term or abbreviation…';clearBtn.textContent=l==='tr'?'Temizle':'Clear';installTitle.textContent=l==='tr'?'Telefonuna uygulama gibi kur':'Install it like an app';installText.textContent=l==='tr'?'Safari’de aç, Paylaş düğmesine bas ve “Ana Ekrana Ekle”yi seç.':'Open in Safari, tap Share, then choose “Add to Home Screen”.';render()}
function pct(a,b){return b?((a/b)*100).toFixed(2)+'%':'—'}function money(v){return isFinite(v)?'£'+v.toLocaleString(undefined,{maximumFractionDigits:2}):'—'}
function calcLTV(){ltvResult.textContent=pct(+ltvLoan.value,+ltvValue.value)}function calcLTC(){ltcResult.textContent=pct(+ltcLoan.value,+ltcCost.value)}function calcLTGDV(){ltgdvResult.textContent=pct(+ltgdvLoan.value,+ltgdvValue.value)}function calcROI(){roiResult.textContent=pct(+roiProfit.value,+roiCost.value)}function calcYield(){yieldResult.textContent=pct(+yieldRent.value,+yieldValue.value)}
function calcDevProfit(){const p=+devGdv.value-+devCost.value;devResult.textContent=`${money(p)} | ${pct(p,+devCost.value)} on cost`}
function calcMonthly(){const P=+loanPrincipal.value,r=(+loanRate.value/100)/12,n=+loanYears.value*12;const m=r&&n?P*r*Math.pow(1+r,n)/(Math.pow(1+r,n)-1):P/n;loanResult.textContent=money(m)}
function calcFee(){feeResult.textContent=money(+feeLoan.value*(+feeRate.value/100))}
function calcRollup(){rollResult.textContent=money(+rollLoan.value*(+rollRate.value/100)*(+rollMonths.value/12))}
function calcConcrete(){cResult.textContent=(+cLen.value*+cWid.value*+cDep.value).toFixed(2)+' m³'}function calcPaint(){const area=+pLen.value*+pHeight.value*+pCoats.value;pResult.textContent=area.toFixed(2)+' m² total coating area'}
function calcFloor(){const a=+fLen.value*+fWid.value*(1+(+fWaste.value/100));fResult.textContent=a.toFixed(2)+' m² incl. waste'}
function calcPB(){const sheets=(+pbArea.value*(1+(+pbWaste.value/100)))/+pbSheet.value;pbResult.textContent=Math.ceil(sheets)+' sheets'}
function calcIns(){const a=+insArea.value*(1+(+insWaste.value/100));insResult.textContent=a.toFixed(2)+' m² incl. waste'}
function calcTiles(){const qty=(+tileArea.value*(1+(+tileWaste.value/100)))/+tileSize.value;tileResult.textContent=Math.ceil(qty)+' tiles'}
q.addEventListener('input',()=>{showPage('knowledge');render()});clearBtn.onclick=()=>{q.value='';activeCat='Tümü';renderCats();render()};trBtn.onclick=()=>setLang('tr');enBtn.onclick=()=>setLang('en');
themeBtn.onclick=()=>{const d=document.documentElement.getAttribute('data-theme')==='dark';document.documentElement.setAttribute('data-theme',d?'light':'dark');localStorage.setItem('emcpTheme',d?'light':'dark')};document.documentElement.setAttribute('data-theme',localStorage.getItem('emcpTheme')||'light');
navHelp.onclick=()=>{sheet.innerHTML=`<button class="close" onclick="closeModal()">×</button><h2>${lang==='tr'?'Çocuk Gibi Anlatılan Kullanım Kılavuzu':'Very Simple User Guide'}</h2><p>${lang==='tr'?'1. Home ekranından bir modüle dokun.<br>2. Knowledge içinde arama yap.<br>3. Calculators bölümünde rakamları yaz ve Calculate’a bas.<br>4. Construction Tools bölümünde ölçüleri gir.<br>5. Koyu mod için üstteki yarım ay düğmesine bas.<br>6. Uygulamayı Safari’de açıp Ana Ekrana Ekle.':'1. Tap a module on Home.<br>2. Search inside Knowledge.<br>3. Enter numbers in Calculators and tap Calculate.<br>4. Enter dimensions in Construction Tools.<br>5. Use the half-moon button for dark mode.<br>6. Open in Safari and Add to Home Screen.'}</p>`;modal.classList.add('show')};
installBtn.onclick=()=>navHelp.click();modal.onclick=e=>{if(e.target.id==='modal')closeModal()};
async function initializeApp(){try{const response=await fetch("data/terms.json");if(!response.ok)throw new Error("Unable to load knowledge data");TERMS=await response.json()}catch(error){console.error("Failed to load knowledge data:",error)}setLang(lang);renderCats();render();updateStats()}
initializeApp();
if("serviceWorker" in navigator)navigator.serviceWorker.register("/service-worker.js");
